### ISSUE TITLE
Sync Sales and Customers

### ISSUE THREAD

**Issue by ThunderCls** [rafdizzle86/woo-lightspeed-customizer#3]
Hey, is there any ways to get this plugin extended to allow for Sales and Customers sync between woocommerce and lightspeed retail?

**Comment by vdrnn** [comment]
I wonder the same. Also, how does the functionality differ to the paid plugins from WooThemes? https://woocommerce.com/products/woocommerce-lightspeed-pos/

**Comment by ThunderCls** [comment]
Well I haven't bought the paid plugin from woocommerce but according their website their plugin only support inventory sync too, so not sure what the difference is or if there's even one

**Comment by rafiyagi** [comment]
This is plugin is meant to extend the functionality of the WooCommerce Lightspeed POS extension. I'm hoping to implement sales and customers sync soon.
